/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Exchange a magic token for a session JWT */
        post: operations["auth-verify"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ingest/missing": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ingest a missing-person report */
        post: operations["ingest-missing"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ingest/project": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ingest an aid project */
        post: operations["ingest-project"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ingest/resource": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ingest a resource */
        post: operations["ingest-resource"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ingest/volunteer": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ingest a volunteer */
        post: operations["ingest-volunteer"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/magic-login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Request a passwordless magic-login token */
        post: operations["magic-login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/missing": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List missing-person reports */
        get: operations["list-missing"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/missing/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a missing-person report by id */
        get: operations["get-missing"];
        /** Replace a missing-person report */
        put: operations["put-missing"];
        post?: never;
        /** Soft-delete a missing-person report */
        delete: operations["delete-missing"];
        options?: never;
        head?: never;
        /** Update a missing-person report */
        patch: operations["patch-missing"];
        trace?: never;
    };
    "/api/v1/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List aid projects */
        get: operations["list-projects"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get an aid project by id */
        get: operations["get-project"];
        /** Replace an aid project */
        put: operations["put-project"];
        post?: never;
        /** Soft-delete an aid project */
        delete: operations["delete-project"];
        options?: never;
        head?: never;
        /** Update an aid project */
        patch: operations["patch-project"];
        trace?: never;
    };
    "/api/v1/resources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List resources */
        get: operations["list-resources"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/resources/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a resource by id */
        get: operations["get-resource"];
        /** Replace a resource */
        put: operations["put-resource"];
        post?: never;
        /** Soft-delete a resource */
        delete: operations["delete-resource"];
        options?: never;
        head?: never;
        /** Update a resource */
        patch: operations["patch-resource"];
        trace?: never;
    };
    "/api/v1/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Aggregate dashboard stats */
        get: operations["stats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Pull entity changes since a cursor */
        get: operations["sync"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/volunteers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List volunteers */
        get: operations["list-volunteers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/volunteers/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a volunteer by id */
        get: operations["get-volunteer"];
        /** Replace a volunteer */
        put: operations["put-volunteer"];
        post?: never;
        /** Soft-delete a volunteer */
        delete: operations["delete-volunteer"];
        options?: never;
        head?: never;
        /** Update a volunteer */
        patch: operations["patch-volunteer"];
        trace?: never;
    };
    "/api/v1/webhook/{source}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Accept a raw inbound webhook payload */
        post: operations["webhook"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AidProject: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/AidProject.json
             */
            readonly $schema?: string;
            category: string;
            contact: string;
            /** Format: date-time */
            created_at: string;
            description: string;
            external_id: string;
            id: string;
            /** Format: double */
            lat?: number;
            /** Format: double */
            lng?: number;
            region: string;
            source: string;
            status: string;
            title: string;
            /** Format: date-time */
            updated_at: string;
            url: string;
        };
        AuthVerifyInputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/AuthVerifyInputBody.json
             */
            readonly $schema?: string;
            /** @description Single-use magic token from magic-login */
            token: string;
        };
        AuthVerifyOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/AuthVerifyOutputBody.json
             */
            readonly $schema?: string;
            access_token: string;
            /** Format: date-time */
            expires_at: string;
            /** @example Bearer */
            token_type: string;
        };
        Change: {
            data: unknown;
            entity: string;
            id: string;
            /** Format: date-time */
            updated_at: string;
        };
        Dataset: {
            data: number[] | null;
            label: string;
        };
        ErrorBody: {
            /** Format: int64 */
            code: number;
            message: string;
        };
        ErrorEnvelope: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/ErrorEnvelope.json
             */
            readonly $schema?: string;
            error: components["schemas"]["ErrorBody"];
        };
        IngestResult: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/IngestResult.json
             */
            readonly $schema?: string;
            /** @description Canonical hub id for the upserted entity */
            id: string;
            /**
             * @description Always 'upserted' on success
             * @example upserted
             */
            status: string;
        };
        ListMissingOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/ListMissingOutputBody.json
             */
            readonly $schema?: string;
            items: components["schemas"]["Person"][] | null;
            /** Format: int64 */
            limit: number;
            /** Format: int64 */
            offset: number;
            /** Format: int64 */
            page: number;
            /** Format: int64 */
            total: number;
        };
        ListProjectsOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/ListProjectsOutputBody.json
             */
            readonly $schema?: string;
            items: components["schemas"]["AidProject"][] | null;
            /** Format: int64 */
            limit: number;
            /** Format: int64 */
            offset: number;
            /** Format: int64 */
            page: number;
            /** Format: int64 */
            total: number;
        };
        ListResourcesOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/ListResourcesOutputBody.json
             */
            readonly $schema?: string;
            items: components["schemas"]["Resource"][] | null;
            /** Format: int64 */
            limit: number;
            /** Format: int64 */
            offset: number;
            /** Format: int64 */
            page: number;
            /** Format: int64 */
            total: number;
        };
        ListVolunteersOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/ListVolunteersOutputBody.json
             */
            readonly $schema?: string;
            items: components["schemas"]["Volunteer"][] | null;
            /** Format: int64 */
            limit: number;
            /** Format: int64 */
            offset: number;
            /** Format: int64 */
            page: number;
            /** Format: int64 */
            total: number;
        };
        MagicLoginInputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/MagicLoginInputBody.json
             */
            readonly $schema?: string;
            /**
             * Format: email
             * @description Email to receive the magic link
             */
            email: string;
        };
        MagicLoginOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/MagicLoginOutputBody.json
             */
            readonly $schema?: string;
            /** Format: date-time */
            expires_at?: string;
            magic_link?: string;
            status: string;
            token?: string;
        };
        MissingInputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/MissingInputBody.json
             */
            readonly $schema?: string;
            /** Format: int64 */
            age?: number;
            contact?: string;
            description?: string;
            external_id: string;
            full_name: string;
            /** Format: date-time */
            last_seen_at?: string;
            last_seen_region?: string;
            /** Format: double */
            lat?: number;
            /** Format: double */
            lng?: number;
            photo_url?: string;
            source: string;
            status?: string;
        };
        PatchMissingInputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/PatchMissingInputBody.json
             */
            readonly $schema?: string;
            /** Format: int64 */
            age?: number;
            contact?: string;
            description?: string;
            full_name?: string;
            last_seen_region?: string;
            photo_url?: string;
            status?: string;
        };
        PatchProjectInputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/PatchProjectInputBody.json
             */
            readonly $schema?: string;
            category?: string;
            contact?: string;
            description?: string;
            /** Format: double */
            lat?: number;
            /** Format: double */
            lng?: number;
            region?: string;
            status?: string;
            title?: string;
            url?: string;
        };
        PatchResourceInputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/PatchResourceInputBody.json
             */
            readonly $schema?: string;
            contact?: string;
            /** Format: double */
            lat?: number;
            /** Format: double */
            lng?: number;
            name?: string;
            /** Format: double */
            quantity?: number;
            region?: string;
            status?: string;
            type?: string;
            unit?: string;
        };
        PatchVolunteerInputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/PatchVolunteerInputBody.json
             */
            readonly $schema?: string;
            availability?: string;
            contact?: string;
            full_name?: string;
            region?: string;
            skills?: string[];
            status?: string;
        };
        Person: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/Person.json
             */
            readonly $schema?: string;
            /** Format: int64 */
            age?: number;
            contact: string;
            /** Format: date-time */
            created_at: string;
            description: string;
            external_id: string;
            full_name: string;
            id: string;
            /** Format: date-time */
            last_seen_at?: string;
            last_seen_region: string;
            /** Format: double */
            lat?: number;
            /** Format: double */
            lng?: number;
            photo_url: string;
            source: string;
            status: string;
            /** Format: date-time */
            updated_at: string;
        };
        ProjectInputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/ProjectInputBody.json
             */
            readonly $schema?: string;
            category?: string;
            contact?: string;
            description?: string;
            /** @description Stable id within the source */
            external_id: string;
            /** Format: double */
            lat?: number;
            /** Format: double */
            lng?: number;
            region?: string;
            /**
             * @description Origin feed/system
             * @example twitter
             */
            source: string;
            status?: string;
            title: string;
            url?: string;
        };
        PutMissingInputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/PutMissingInputBody.json
             */
            readonly $schema?: string;
            /** Format: int64 */
            age?: number;
            contact?: string;
            description?: string;
            full_name: string;
            last_seen_region?: string;
            photo_url?: string;
            status?: string;
        };
        PutProjectInputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/PutProjectInputBody.json
             */
            readonly $schema?: string;
            category?: string;
            contact?: string;
            description?: string;
            /** Format: double */
            lat?: number;
            /** Format: double */
            lng?: number;
            region?: string;
            status?: string;
            title: string;
            url?: string;
        };
        PutResourceInputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/PutResourceInputBody.json
             */
            readonly $schema?: string;
            contact?: string;
            /** Format: double */
            lat?: number;
            /** Format: double */
            lng?: number;
            name: string;
            /** Format: double */
            quantity?: number;
            region?: string;
            status?: string;
            type?: string;
            unit?: string;
        };
        PutVolunteerInputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/PutVolunteerInputBody.json
             */
            readonly $schema?: string;
            availability?: string;
            contact?: string;
            full_name: string;
            region?: string;
            skills?: string[] | null;
            status?: string;
        };
        RecentEntities: {
            missing: components["schemas"]["Person"][] | null;
            projects: components["schemas"]["AidProject"][] | null;
            resources: components["schemas"]["Resource"][] | null;
            volunteers: components["schemas"]["Volunteer"][] | null;
        };
        Resource: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/Resource.json
             */
            readonly $schema?: string;
            contact: string;
            /** Format: date-time */
            created_at: string;
            external_id: string;
            id: string;
            /** Format: double */
            lat?: number;
            /** Format: double */
            lng?: number;
            name: string;
            /** Format: double */
            quantity: number;
            region: string;
            source: string;
            status: string;
            type: string;
            unit: string;
            /** Format: date-time */
            updated_at: string;
        };
        ResourceInputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/ResourceInputBody.json
             */
            readonly $schema?: string;
            contact?: string;
            external_id: string;
            /** Format: double */
            lat?: number;
            /** Format: double */
            lng?: number;
            name: string;
            /** Format: double */
            quantity?: number;
            region?: string;
            source: string;
            status?: string;
            type?: string;
            unit?: string;
        };
        StatsData: {
            by_region: {
                [key: string]: {
                    [key: string]: number;
                };
            };
            by_status: {
                [key: string]: {
                    [key: string]: number;
                };
            };
            counts: {
                [key: string]: number;
            };
            recent: components["schemas"]["RecentEntities"];
            timeline: components["schemas"]["Timeline"];
        };
        StatsOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/StatsOutputBody.json
             */
            readonly $schema?: string;
            data: components["schemas"]["StatsData"];
        };
        SyncOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/SyncOutputBody.json
             */
            readonly $schema?: string;
            changes: components["schemas"]["Change"][] | null;
            /** Format: int64 */
            count: number;
            /** @description Pass as since on the next call (latest updated_at in this page). */
            cursor: string;
        };
        Timeline: {
            datasets: components["schemas"]["Dataset"][] | null;
            labels: string[] | null;
        };
        Volunteer: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/Volunteer.json
             */
            readonly $schema?: string;
            availability: string;
            contact: string;
            /** Format: date-time */
            created_at: string;
            external_id: string;
            full_name: string;
            id: string;
            region: string;
            skills: string[] | null;
            source: string;
            status: string;
            /** Format: date-time */
            updated_at: string;
        };
        VolunteerInputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/VolunteerInputBody.json
             */
            readonly $schema?: string;
            availability?: string;
            contact?: string;
            external_id: string;
            full_name: string;
            region?: string;
            skills?: string[] | null;
            source: string;
            status?: string;
        };
        WebhookOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/WebhookOutputBody.json
             */
            readonly $schema?: string;
            id: string;
            /** @example queued */
            status: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    "auth-verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AuthVerifyInputBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthVerifyOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    "ingest-missing": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MissingInputBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngestResult"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    "ingest-project": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectInputBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngestResult"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    "ingest-resource": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResourceInputBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngestResult"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    "ingest-volunteer": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VolunteerInputBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngestResult"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    "magic-login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MagicLoginInputBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MagicLoginOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    "list-missing": {
        parameters: {
            query?: {
                /** @description Filter by region */
                region?: string;
                /** @description Filter by status */
                status?: string;
                /** @description Free-text search */
                q?: string;
                /** @description created_at >= this (YYYY-MM-DD or RFC3339) */
                from?: string;
                /** @description created_at <= this (YYYY-MM-DD or RFC3339) */
                to?: string;
                limit?: number;
                offset?: number;
                /** @description Near-me center latitude (with radius_km) */
                lat?: number;
                /** @description Near-me center longitude (with radius_km) */
                lng?: number;
                /** @description Near-me radius in km; >0 activates near-me */
                radius_km?: number;
            };
            header?: {
                Authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListMissingOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    "get-missing": {
        parameters: {
            query?: never;
            header?: {
                Authorization?: string;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Person"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    "put-missing": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PutMissingInputBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Person"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    "delete-missing": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    "patch-missing": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PatchMissingInputBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Person"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    "list-projects": {
        parameters: {
            query?: {
                /** @description Filter by region */
                region?: string;
                /** @description Filter by status */
                status?: string;
                /** @description Free-text search */
                q?: string;
                /** @description created_at >= this (YYYY-MM-DD or RFC3339) */
                from?: string;
                /** @description created_at <= this (YYYY-MM-DD or RFC3339) */
                to?: string;
                limit?: number;
                offset?: number;
                /** @description Filter by category */
                category?: string;
            };
            header?: {
                Authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListProjectsOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    "get-project": {
        parameters: {
            query?: never;
            header?: {
                Authorization?: string;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AidProject"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    "put-project": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PutProjectInputBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AidProject"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    "delete-project": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    "patch-project": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PatchProjectInputBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AidProject"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    "list-resources": {
        parameters: {
            query?: {
                /** @description Filter by region */
                region?: string;
                /** @description Filter by status */
                status?: string;
                /** @description Free-text search */
                q?: string;
                /** @description created_at >= this (YYYY-MM-DD or RFC3339) */
                from?: string;
                /** @description created_at <= this (YYYY-MM-DD or RFC3339) */
                to?: string;
                limit?: number;
                offset?: number;
                /** @description Filter by resource type */
                type?: string;
            };
            header?: {
                Authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListResourcesOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    "get-resource": {
        parameters: {
            query?: never;
            header?: {
                Authorization?: string;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Resource"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    "put-resource": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PutResourceInputBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Resource"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    "delete-resource": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    "patch-resource": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PatchResourceInputBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Resource"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    stats: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatsOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    sync: {
        parameters: {
            query?: {
                /** @description RFC3339 timestamp; returns changes strictly after it. Empty = from epoch. */
                since?: string;
                /** @description Max changes to return (1-1000). */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SyncOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    "list-volunteers": {
        parameters: {
            query?: {
                /** @description Filter by region */
                region?: string;
                /** @description Filter by status */
                status?: string;
                /** @description Free-text search */
                q?: string;
                /** @description created_at >= this (YYYY-MM-DD or RFC3339) */
                from?: string;
                /** @description created_at <= this (YYYY-MM-DD or RFC3339) */
                to?: string;
                limit?: number;
                offset?: number;
                /** @description Filter by a skill the volunteer has */
                skill?: string;
            };
            header?: {
                Authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListVolunteersOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    "get-volunteer": {
        parameters: {
            query?: never;
            header?: {
                Authorization?: string;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Volunteer"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    "put-volunteer": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PutVolunteerInputBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Volunteer"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    "delete-volunteer": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    "patch-volunteer": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PatchVolunteerInputBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Volunteer"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    webhook: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Identifier of the upstream system */
                source: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/octet-stream": string;
            };
        };
        responses: {
            /** @description Accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WebhookOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
}
